---
title: "planning_doc"
output: word_document
params:
  YYYYMMDD: YYYY-MM-DD
  slug: slug
  sharepoint: [sharepoint]
  workshop_website: [workshop website]
  workshop_website_source: [workshop_website_source]
  registration_page: [registration page]
  lesson_content: [lesson_content]
  lead_instructor: [lead instructor]
  instructor: [instructor]
  helper: [helper]
  set_title: "Planning doc"
  file: data.csv
  show_text: TRUE
---

---
title: `r params$set_title`
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

* Plan in Planner `r params$planner`
* Team Channel
* `r params$sharepoint`
* `r params$workshop_website `
* `r params$workshop_website_source `
* `r params$lesson_content `
* Slides (optional)
* `r params$registration_page`
* Collaborative Documents 1,2,3,4
* Pre-workshop survey and results
* Post-workshop survey and results
* Debriefing document
* Participants Spreadsheet
* Zoom Link

### Training team:  `r params$training_team`

### Training team general roles:
When not teaching, a training team member can do the following things:

* Add more information or help the other instructor to clarify some points.
* Check the room for people that have questions or are having difficulties following and can bring this to the attention of the teaching instructor to suggest spending more time on a certain topic (only if necessary).
* Can tell teaching Instructor when to slow down or speed up.
* Be on the lookout for help post-its. Walk around to help attendees with small questions.

### Instructors:  `r params$instructor`
#### [An instructor is a person who teaches in the workshop. There must be two or more instructors (including the Lead Instructor) in every workshop. In the Carpentries workshops (Software Carpentry or Data Carpentry) at least one of the instructors needs to be certified by the Carpentries.] 

### Lead Instructor:  `r params$lead_instructor`
#### [Lead Instructor is an Instructor who is also responsible for some of the preparatory tasks as well as hosting most of the workshop. They also have the responsibilities of an Instructor (see below).] 
### Lead instructor specific roles:

* The lead instructor is the responsible person for making sure the workshop is well organized and all content is accessible.
* Prepares the workshop website, collaborative documents, and exercises document.
* Prepares general introduction (see slides for NLeSCs intro) + icebreaker.
* Makes sure to gather feedback from the participants at least every 4 hours (carpentries guidelines) for example via asking for tip/tops.
* Prepares planning, calibration and debriefing meetings.
* Ensures that everyone on the team knows their roles and responsibilities.

### Helpers: `r params$helper`
#### [Follow the chat and the collaborative document during the workshop, and answer participants’ questions. Also help them troubleshoot issues. They bring up questions to instructor’s attention if they think the question is relevant and timely] 

### Helper specific roles:

#### In-person workshop host 

* Welcomes everyone at the entrance of the workshop room (usually upstairs in the Matrix building, Sacha or Fenne will be downstairs).
* Gives people their badges and sticky notes.
* Checks people off the participants list (please do this every day, not just on day 1).
* Checks the room for people that have questions or are having difficulties following and can bring this to the attention of the instructors to suggest to spend more time on a certain topic (only if necessary).
* Walks around to help attendees with small questions.
* Can tell teaching Instructor when to slow down or speed up.
* Writes down things that went well and things to improve in the debriefing document.

#### Zoom host 

* Ensures all the Instructors and Helpers are co-hosts. 
* Lets people in from the waiting room, after checking if they are on the participants list. 
* Keeps the participants list updated. 
* Mutes and unmutes participants. 
* Keeps nonverbal feedback icons clean (lowers hands, etc). 
* Manages breakout rooms 
* Keeps an eye on the chat 
* Answers questions in the chat 
* Brings questions and issues to the attention of the teaching Instructor 
* Tells teaching Instructor when to slow down or speed up 
* Writes down things that went well and things to improve in the debriefing document.

#### Note keeper: 
(ideally not the person who was teaching on that day)  

* Makes notes in the collaborative document 
* Makes the log of all commands typed in by the Instructor 
* Pastes exercises 
* Keeps collaborative document clean 

### Schedule & Teaching Division

| Date | Lesson | Instructor | Designated Survivor | Zoom host | Note taker |
|---|---|---|---|---|---|
|   |   |   |   |   |   |


## Calibration meeting (instructors + workshop coordinator, week before the workshop)

### YYYY-MM-DD

### Roll Call for this meeting

#### Discussion Points & Notes

* Pre-workshop survey
* Welcome procedure
* Review Tasks
* For external workshops: check the number of hours you have written so far and keep track of them in the table at the end of this document
* Make sure the training team can contact each other in case a train is delayed or someone gets sick (confirm your way of communication via whatapp/teams/any way you prefer).

## Planning meeting (3 weeks before the workshop)

### YYYY-MM-DD

### Roll Call for this meeting

#### Discussion Points & Notes

* Confirm the Lead Instructor (chairs the meeting)
* Assign note taker for this meeting (one of the helpers)
* Select curriculum
* Assign teaching
* Assign helpers’ roles (designated survivor, Zoom Host, Note taker)
* Decide on setup sessions
* Additional pre-workshop survey questions needed?
* One person needed to help setting up and restoring the classroom
* For external workshops: check the hours that are available and the exact code with the Training Coordinator, put them at the end of this document. Please keep track of the hours you have written in the table at the end of the document.
* Assign Tasks in Planner, set deadlines.

### Table for keeping hours for external workshops

| Instructor Name | Date | Prep & follow-up Hours | Hours on teaching itself | total hours written |
|---|---|---|---|---|
|   |   |   |   |   |

